project_id = "pasfkwniarukkdfdclah"

[functions.create-guest-booking]
verify_jwt = false

[functions.process-outbox]
verify_jwt = false

[functions.admin-clear-all-bookings]
verify_jwt = false

[functions.admin-delete-provider]
verify_jwt = false
